import { fields } from "@keystatic/core";
import pageKeys from "./page-keys.json";

/**
 * The `pages`/`settings` content collections store copy as flat, per-page
 * dotted-key maps (`copy.strings`, `copy.lists`, `copy.cards`) rather than a
 * fixed set of fields — each page's keys are defined by its Astro template,
 * not by a shared schema. Keystatic fields are statically typed, so instead
 * of hand-writing ~500 field definitions (or migrating the YAML to a
 * different shape), this builds fields from a precomputed manifest of each
 * file's current keys (`keystatic/page-keys.json`, regenerated by
 * `pnpm keystatic:sync-fields`). keystatic.config.ts is bundled for both the
 * server and the browser (Keystatic's form UI runs client-side), so it can't
 * read the YAML files directly at runtime the way a Node-only script could —
 * hence the separate, checked-in JSON manifest instead of `node:fs`.
 */

type Manifest = {
  pages: Record<string, { strings: string[]; lists: string[]; cards: string[] }>;
  settings: Record<string, { strings: string[]; lists: string[]; cards: string[] }>;
};

const manifest = pageKeys as Manifest;

function cardField() {
  return fields.object(
    {
      title: fields.text({ label: "Title" }),
      description: fields.text({ label: "Description", multiline: true }),
      label: fields.text({ label: "Link label (optional)" }),
      href: fields.text({ label: "Link href (optional)" }),
    },
    { label: "Card" }
  );
}

export function copyFieldsFor(kind: "pages" | "settings", name: string) {
  const keys = manifest[kind][name] ?? { strings: [], lists: [], cards: [] };

  const stringFields = Object.fromEntries(
    keys.strings.map((key) => [key, fields.text({ label: key, multiline: true })])
  );

  const listFields = Object.fromEntries(
    keys.lists.map((key) => [
      key,
      fields.array(fields.text({ label: "Item", multiline: true }), {
        label: key,
        itemLabel: (props) => props.value || "Item",
      }),
    ])
  );

  const cardFields = Object.fromEntries(
    keys.cards.map((key) => [
      key,
      fields.array(cardField(), {
        label: key,
        itemLabel: (props) => props.fields.title.value || "Card",
      }),
    ])
  );

  return fields.object(
    {
      strings: fields.object(stringFields, { label: "Strings" }),
      lists: fields.object(listFields, { label: "Lists" }),
      cards: fields.object(cardFields, { label: "Cards" }),
    },
    { label: "Copy" }
  );
}
